<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>toDo App</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 10px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-top: 20px;
                margin-bottom: 0;
            }

            .container {
                width: 20%;
                border: 2px solid #719e40;
                border-radius: 5px;
                margin-left: 5px;
            }

            button {
                margin-bottom: 5px;
            }
        </style>§
    </head>
    <body>
        <h1>Slim Todo App</h1>
        <div>Keeping track of stuff</div>

        <div class='container'>
            <h2>ToDo Name</h2>
            <p>Details of the Todo</p>
            <h4>Urgent-Important</h4>
            <button class='btnEdit'>Edit</button>
            <button class='btnDelete'>Delete</button>
            <button class='btnComplete'>Complete</button>
        </div>

    <button class='btnAdd'>Add new ToDo</button>
    </body>
</html>
