<?php
require_once('functions.php')
?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>toDo App</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css' />
        <link rel='stylesheet' type='text/css' href='./css/style.css' />
    </head>
    <body>
        <h1>Slim Todo App</h1>
        <div>Keeping track of stuff</div>
        <div class='content'>
            <?php $result = displayToDo($toDo); echo $result; ?>
        </div>
    <div class='addBtn' style='background: red'>
    <button class='btnAdd'>Add new ToDo</button>
    </div>

    </body>
</html>
